-- ============================================================
-- BASELINE SCHEMA CAPTURE — reconstructed from live production
-- introspection query output pasted into the assistant, not
-- generated by `supabase db dump` (CLI auth was not available
-- in this environment).
--
-- Section: POLICIES — current production state.
--
-- Transcribed verbatim from the pasted pg_policy query output.
-- No statements below were inferred, reordered, or cleaned up.
-- Table CREATE statements, RLS enable flags, and constraints
-- are not yet included — those come from separate pasted
-- batches (constraints, then columns) per the user's plan.
-- ============================================================

-- ── artist_delegates ──────────────────────────────────────────

CREATE POLICY "artist_delegates_delete" ON artist_delegates
  FOR DELETE
  USING (auth.uid() = artist_id);

CREATE POLICY "artist_delegates_insert" ON artist_delegates
  FOR INSERT
  WITH CHECK (auth.uid() = artist_id);

CREATE POLICY "artist_delegates_select" ON artist_delegates
  FOR SELECT
  USING ((auth.uid() = artist_id) OR (auth.uid() = delegate_id));

CREATE POLICY "artist_delegates_update" ON artist_delegates
  FOR UPDATE
  USING (auth.uid() = delegate_id);

-- ── attachments ────────────────────────────────────────────────

CREATE POLICY "attachments_own" ON attachments
  FOR ALL
  USING (EXISTS ( SELECT 1
   FROM performances
  WHERE ((performances.id = attachments.performance_id) AND (performances.user_id = auth.uid()))));

-- ── beta_invites ───────────────────────────────────────────────

CREATE POLICY "service_role_all" ON beta_invites
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

CREATE POLICY "users_accept_own_invite" ON beta_invites
  FOR UPDATE
  TO authenticated
  USING (email = (auth.jwt() ->> 'email'::text))
  WITH CHECK (email = (auth.jwt() ->> 'email'::text));

CREATE POLICY "users_read_own_invite" ON beta_invites
  FOR SELECT
  USING (email = (auth.jwt() ->> 'email'::text));

-- ── capture_sessions ───────────────────────────────────────────

CREATE POLICY "capture_sessions_own" ON capture_sessions
  FOR ALL
  USING (EXISTS ( SELECT 1
   FROM performances
  WHERE ((performances.id = capture_sessions.performance_id) AND (performances.user_id = auth.uid()))));

-- ── catalogue_fallback ─────────────────────────────────────────

CREATE POLICY "Authenticated users can read catalogue_fallback" ON catalogue_fallback
  FOR SELECT
  TO authenticated
  USING (true);

-- ── compositions ───────────────────────────────────────────────

CREATE POLICY "compositions_read" ON compositions
  FOR SELECT
  USING (auth.role() = 'authenticated'::text);

-- ── detection_events ───────────────────────────────────────────

CREATE POLICY "detection_events_own" ON detection_events
  FOR SELECT
  TO authenticated
  USING (EXISTS ( SELECT 1
   FROM performances
  WHERE ((performances.id = detection_events.performance_id) AND (performances.user_id = auth.uid()))));

-- ── manual_song_events ─────────────────────────────────────────

CREATE POLICY "Users see own manual events" ON manual_song_events
  FOR ALL
  USING (auth.uid() = user_id);

-- ── performance_songs ──────────────────────────────────────────

CREATE POLICY "songs_own" ON performance_songs
  FOR ALL
  USING (EXISTS ( SELECT 1
   FROM performances
  WHERE ((performances.id = performance_songs.performance_id) AND (performances.user_id = auth.uid()))));

-- ── performances ───────────────────────────────────────────────

CREATE POLICY "performances_own" ON performances
  FOR ALL
  USING (auth.uid() = user_id);

CREATE POLICY "users_insert_own_performance" ON performances
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- ── planned_setlist_songs ──────────────────────────────────────

CREATE POLICY "Users can manage their own planned setlist songs" ON planned_setlist_songs
  FOR ALL
  USING (EXISTS ( SELECT 1
   FROM planned_setlists
  WHERE ((planned_setlists.id = planned_setlist_songs.planned_setlist_id) AND (planned_setlists.user_id = auth.uid()))))
  WITH CHECK (EXISTS ( SELECT 1
   FROM planned_setlists
  WHERE ((planned_setlists.id = planned_setlist_songs.planned_setlist_id) AND (planned_setlists.user_id = auth.uid()))));

-- ── planned_setlists ───────────────────────────────────────────

CREATE POLICY "Users can manage their own planned setlists" ON planned_setlists
  FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- ── pro_reports ────────────────────────────────────────────────

CREATE POLICY "pro_reports_self" ON pro_reports
  FOR ALL
  USING (show_id IN ( SELECT shows.id
   FROM shows
  WHERE (shows.created_by = auth.uid())));

-- ── profiles ───────────────────────────────────────────────────

CREATE POLICY "Service role can insert profiles" ON profiles
  FOR INSERT
  TO service_role
  WITH CHECK (true);

CREATE POLICY "profiles_self" ON profiles
  FOR ALL
  USING (auth.uid() = id);

-- ── publisher_accounts ─────────────────────────────────────────

CREATE POLICY "publisher_accounts_admin" ON publisher_accounts
  FOR ALL
  USING (EXISTS ( SELECT 1
   FROM profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'admin'::text))));

CREATE POLICY "publisher_accounts_own" ON publisher_accounts
  FOR ALL
  USING (auth.uid() = user_id);

-- ── publisher_invites ──────────────────────────────────────────

CREATE POLICY "publisher_invites_admin" ON publisher_invites
  FOR ALL
  USING (EXISTS ( SELECT 1
   FROM profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'admin'::text))));

CREATE POLICY "publisher_invites_own" ON publisher_invites
  FOR ALL
  USING (EXISTS ( SELECT 1
   FROM publisher_accounts
  WHERE ((publisher_accounts.id = publisher_invites.publisher_id) AND (publisher_accounts.user_id = auth.uid()))));

-- ── publisher_roster ───────────────────────────────────────────

CREATE POLICY "publisher_roster_admin" ON publisher_roster
  FOR ALL
  USING (EXISTS ( SELECT 1
   FROM profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'admin'::text))));

CREATE POLICY "publisher_roster_own" ON publisher_roster
  FOR ALL
  USING (EXISTS ( SELECT 1
   FROM publisher_accounts
  WHERE ((publisher_accounts.id = publisher_roster.publisher_id) AND (publisher_accounts.user_id = auth.uid()))));

-- ── rd_log ─────────────────────────────────────────────────────

CREATE POLICY "rd_log_superadmin_all" ON rd_log
  FOR ALL
  USING ((auth.jwt() ->> 'email'::text) = ANY (ARRAY['jesse.slack.music@gmail.com'::text, 'darylscottsongs@gmail.com'::text]))
  WITH CHECK ((auth.jwt() ->> 'email'::text) = ANY (ARRAY['jesse.slack.music@gmail.com'::text, 'darylscottsongs@gmail.com'::text]));

-- ── setlist_items ──────────────────────────────────────────────

CREATE POLICY "setlist_items_self" ON setlist_items
  FOR ALL
  USING (setlist_id IN ( SELECT setlists.id
   FROM setlists
  WHERE (setlists.show_id IN ( SELECT shows.id
           FROM shows
          WHERE (shows.created_by = auth.uid())))));

-- ── setlist_songs ──────────────────────────────────────────────

CREATE POLICY "setlist_songs_self" ON setlist_songs
  FOR ALL
  USING (performance_id IN ( SELECT performances.id
   FROM performances
  WHERE (performances.user_id = auth.uid())));

-- ── setlists ───────────────────────────────────────────────────

CREATE POLICY "setlists_self" ON setlists
  FOR ALL
  USING (show_id IN ( SELECT shows.id
   FROM shows
  WHERE (shows.created_by = auth.uid())));

-- ── show_artists ───────────────────────────────────────────────

CREATE POLICY "show_artists_self" ON show_artists
  FOR ALL
  USING (show_id IN ( SELECT shows.id
   FROM shows
  WHERE (shows.created_by = auth.uid())));

-- ── shows ──────────────────────────────────────────────────────

CREATE POLICY "shows_self" ON shows
  FOR ALL
  USING (created_by = auth.uid());

CREATE POLICY "users_insert_own_show" ON shows
  FOR INSERT
  WITH CHECK (auth.uid() = created_by);

-- ── user_song_performances ─────────────────────────────────────

CREATE POLICY "user_song_performances_self" ON user_song_performances
  FOR ALL
  USING (user_id = auth.uid());

-- ── user_song_rejections ───────────────────────────────────────

CREATE POLICY "user_song_rejections_self" ON user_song_rejections
  FOR ALL
  USING (user_id = auth.uid());

-- ── user_songs ─────────────────────────────────────────────────

CREATE POLICY "user_songs_self" ON user_songs
  FOR ALL
  USING (user_id = auth.uid());

-- ── venues ─────────────────────────────────────────────────────

CREATE POLICY "venues_insert" ON venues
  FOR INSERT
  WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "venues_read" ON venues
  FOR SELECT
  USING (true);

-- ── waitlist ───────────────────────────────────────────────────

CREATE POLICY "waitlist_insert" ON waitlist
  FOR INSERT
  WITH CHECK (true);
