-- R&D Activity Log — Daryl Scott retroactive entries
-- team_member: Daryl | role: Co-Founder / President | is_retroactive: true
-- Table and RLS already created in rd_log.sql — inserts only.

insert into rd_log (
  entry_date, team_member, role, workstream,
  technical_problem, work_performed, hours,
  outcome, remaining_uncertainty, related_file,
  funding_relevance, is_retroactive
) values

('2026-01-15', 'Daryl', 'Co-Founder / President', 'Product Concept and Royalty Workflow Design',
 'Identified the core missed royalty problem: artists not submitting live setlists resulting in uncollected PRO distributions. Explored whether automated live audio capture could reduce missed royalties.',
 'Defined core problem. Identified artists, managers, labels, publishers, PROs, and venues as users. Framed product as royalty capture tool and live performance data platform.',
 30,
 'Product frame established. Royalty capture + live data platform thesis defined.',
 'Whether live song performance data could be captured reliably and scalably without manual entry by the artist.',
 'Product strategy docs',
 ARRAY['Section 41', 'IRAP'],
 true),

('2026-01-15', 'Daryl', 'Co-Founder / President', 'PRO Submission Workflow Research',
 'Research how SOCAN, ASCAP, BMI, PRS and other PROs accept live performance submissions and what data they require.',
 'Researched SOCAN, ASCAP, BMI, PRS submission workflows. Identified data requirements per PRO. Mapped submission friction points. Identified that small venue shows are systematically excluded from PRO sampling models.',
 25,
 'PRO submission workflow mapped. Key insight: small venues excluded from sampling = uncollected royalties pool into black-box distributions.',
 'Different PROs have different submission systems, rules, formats, and API availability.',
 'PRO research notes',
 ARRAY['Section 41', 'IRAP', 'NSF SBIR'],
 true),

('2026-02-01', 'Daryl', 'Co-Founder / President', 'Business Model and Data Infrastructure Planning',
 'Define how Setlistr generates revenue and what the long-term data asset looks like at scale.',
 'Developed Tool → Habit → Network → Infrastructure strategic frame. Defined SaaS wedge + data asset thesis. Mapped three-layer moat: user lock-in → operational dependency → institutional lock-in. Modeled publisher terminal as B2B revenue layer.',
 25,
 'Business model documented. Publisher terminal identified as primary B2B revenue. Data asset framing established for investor narrative.',
 'How to price the publisher terminal. Which publishers to approach first.',
 'Business plan docs',
 ARRAY['Section 41'],
 true),

('2026-02-01', 'Daryl', 'Co-Founder / President', 'Market Problem and Royalty Gap Research',
 'Quantify the size of the uncollected live performance royalty problem to build investor and grant narrative.',
 'Researched PRO sampling model limitations. Documented that small venues under 500 capacity are systematically excluded. Researched black-box distribution pools. Built market sizing narrative around trapped royalty capital.',
 20,
 'Market size documented. Core insight confirmed: money already exists in PRO pools, just waiting for verified performance data to unlock distribution.',
 'Exact size of uncollected royalty pool not publicly disclosed by PROs.',
 'Research notes',
 ARRAY['Section 41', 'NSF SBIR'],
 true),

('2026-03-01', 'Daryl', 'Co-Founder / President', 'Live Audio Capture Strategy Research',
 'Research optimal audio capture approach for live performance environments: chunk size, recognition frequency, battery impact, background audio limitations.',
 'Researched 12-15 second audio chunk approach. Explored show lengths of 60-90 minutes. Evaluated battery usage and microphone permission implications. Researched background audio limitations on iOS PWA. Identified Capacitor as potential solution.',
 20,
 'Capture strategy defined: 12-second chunks, 20-second intervals. Background audio identified as core unresolved problem on iOS.',
 'What chunk length produces best recognition accuracy while controlling cost, latency, and duplicate detections.',
 'Strategy docs',
 ARRAY['Section 41', 'IRAP', 'NSF SBIR'],
 true),

('2026-04-01', 'Daryl', 'Co-Founder / President', 'Terms of Service — Audio Processing and Privacy',
 'Draft Terms of Service covering audio fingerprinting, live performance data, PRO submission, user content, and platform liability.',
 'Drafted full Terms of Service document. Covered: audio fingerprinting disclosure, no long-term stored live audio, third-party recognition services, user content and metadata, PRO submissions, royalty estimates and disclaimers, authority to submit on behalf of artists.',
 35,
 'Terms of Service drafted. Key decisions: no stored live audio, fingerprint-only processing, explicit user confirmation before PRO submission.',
 'Must balance processing enough audio to identify songs while minimizing privacy risk. Governing law and dispute resolution placeholders need Delaware entity confirmation.',
 'setlistr-2/docs/ToS',
 ARRAY['Section 41'],
 true),

('2026-04-01', 'Daryl', 'Co-Founder / President', 'Privacy Policy Research and Drafting',
 'Research App Store privacy policy requirements and draft a Privacy Policy for Setlistr covering audio data, user data, and third-party services.',
 'Researched Apple App Store and Google Play privacy policy requirements. Identified that a live accessible Privacy Policy URL is required before app store approval. Began drafting policy covering: data collected, audio fingerprinting methodology, third-party services (ACRCloud, Supabase, Vercel), user rights, GDPR and CCPA compliance.',
 20,
 'Privacy Policy scope defined. App Store blocker identified. Drafting in progress.',
 'GDPR compliance for European users requires data portability rights. COPPA implications for under-13 users need clarification.',
 'Privacy Policy draft',
 ARRAY['Section 41'],
 true),

('2026-04-01', 'Daryl', 'Co-Founder / President', 'Investor Narrative and Pitch Deck Development',
 'Build investor pitch materials that communicate Setlistr''s infrastructure thesis and market opportunity to sophisticated investors.',
 'Drafted pitch deck narrative. Developed trapped capital framing: PROs sitting on billions they cannot accurately distribute because the data doesn''t exist. Built three-layer moat explanation. Drafted financial projections: publisher terminal at $349/mo blended, Year 1 = 10 accounts, Year 2 = 50, Year 3 = 200.',
 30,
 'Pitch deck drafted. Core investor narrative: SaaS is the wedge, data is the asset, infrastructure is the scale. Doug Merritt committed as lead investor April 10.',
 'How to price publisher terminal tiers. Which publishers to approach for design partner conversations.',
 'Pitch deck / business plan',
 ARRAY['Section 41'],
 true),

('2026-04-01', 'Daryl', 'Co-Founder / President', 'Grant Research — NSF SBIR Technical Positioning',
 'Research NSF SBIR eligibility and develop the technical innovation narrative for AI topic application.',
 'Researched NSF SBIR AI topic requirements. Developed technical innovation framing: AI-assisted live performance attribution for environments excluded from PRO sampling models. Identified Phase I (~$275K) and Phase II (up to $2M) pathway. Confirmed Jesse qualifies as PI at 20+ hrs/week. Drafted Project Pitch outline.',
 25,
 'NSF SBIR application strategy defined. Core pitch framing: not just song ID — novel AI system for verified performance attribution at excluded venues.',
 'Grant narrative must prove Setlistr is developing novel infrastructure, not merely applying existing recognition APIs.',
 'NSF SBIR research docs',
 ARRAY['Section 41', 'NSF SBIR'],
 true),

('2026-04-01', 'Daryl', 'Co-Founder / President', 'Grant Research — IRAP Canada R&D Funding',
 'Research IRAP (Industrial Research Assistance Program) eligibility for Setlistr as a Canadian-founder company with genuine technical R&D.',
 'Researched IRAP eligibility criteria. Confirmed Jesse''s Canadian citizenship as qualifying factor. Mapped Setlistr''s audio recognition, transcription fallback, structured verification, and live performance data infrastructure work to IRAP R&D categories. Identified IRAP as non-dilutive funding path parallel to NSF SBIR.',
 20,
 'IRAP identified as viable parallel funding path. Technical R&D work maps cleanly to IRAP eligibility criteria.',
 'IRAP requires documented evidence of R&D activities. Retroactive documentation process needs to be established.',
 'IRAP research docs',
 ARRAY['Section 41', 'IRAP'],
 true),

('2026-04-01', 'Daryl', 'Co-Founder / President', 'Patent Strategy and IP Brainstorming',
 'Identify which Setlistr technical innovations are patentable and develop provisional patent application strategy.',
 'Identified potential patent claims: automated PRO submission using real-time audio recognition, confidence-weighted song identification using artist history and expected setlists, vendor-agnostic recognition adapter, normalized confidence scoring, silence/audio-energy-based session demarcation, multi-artist live performance data infrastructure, setlist reconstruction from partial recognition events. Researched provisional patent application process.',
 25,
 '9 provisional patent applications filed (PPA-001 through PPA-009). Patent strategy documented.',
 'Which claims are truly novel and defensible vs. standard product features. Need patent counsel to evaluate.',
 'Patent strategy docs',
 ARRAY['Section 41', 'Patent'],
 true),

('2026-04-01', 'Daryl', 'Co-Founder / President', 'Co-Founder Agreement and IP Assignment',
 'Draft and execute legal agreements establishing equity structure, IP assignment, and founder obligations.',
 'Drafted Co-Founder Agreement: 50/50 equity split, four-year vest, one-year cliff, Jesse as CEO, Daryl as COO. Drafted IP Assignment Agreement transferring all pre-company IP to Setlistr Inc. Both documents signed by Jesse Slack and Daryl Scott.',
 15,
 'Co-Founder Agreement and IP Assignment Agreement executed. Equity structure formalized.',
 'Equity incentive plan for contractors and future employees needs to be established. Wilson Sonsini consultation needed.',
 'Signed legal documents',
 ARRAY['Section 41'],
 true),

('2026-05-01', 'Daryl', 'Co-Founder / President', 'SOCAN Grant Research',
 'Research SOCAN Foundation organization grant stream eligibility for Setlistr as a platform serving SOCAN member artists.',
 'Researched SOCAN Foundation grant programs. Identified organization grant stream as applicable to platforms benefiting SOCAN members. Reviewed SOCAN annual report noting 16.1% YoY increase in concert royalty collection and stated investment in tech infrastructure. Prepared outreach to SOCAN Foundation referencing Liam Russell relationship.',
 15,
 'SOCAN Foundation grant application strategy defined. September board cycle identified as target submission window.',
 'SOCAN Foundation may not fund for-profit technology companies. Eligibility for organization stream needs confirmation.',
 'Grant research docs',
 ARRAY['Section 41', 'IRAP'],
 true),

('2026-05-01', 'Daryl', 'Co-Founder / President', 'Accelerator and Funding Program Research',
 'Research all available accelerator programs, startup grants, cloud credits, and non-dilutive funding sources applicable to Setlistr.',
 'Researched: Project Music Nashville EC, Music Ally SI:X, ASCAP Lab, Abbey Road Red, Y Combinator, NSF SBIR, LaunchTN SBIR Matching Fund, AWS Activate, Google for Startups, Vercel and Supabase startup programs, Mercury banking credits, MiddleGame Ventures, UTA Ventures, Yamaha Music Innovations Fund, Deciens Capital, Federal R&D Tax Credit Section 41. Built comprehensive tracker with priority, deadline, owner, and exact next action for each resource.',
 30,
 'Full resource map completed. 33 programs identified and prioritized. Lane split established: Jesse owns USPTO TN pro bono, Project Music, SOCAN, ASCAP Lab, cloud credits. Daryl owns VLA patent pro bono, grant research.',
 'Application deadlines vary. Some programs (NSF SBIR) require significant preparation. Competitive programs need strong technical narrative.',
 'Grant tracker spreadsheet',
 ARRAY['Section 41', 'IRAP', 'NSF SBIR'],
 true),

('2026-05-01', 'Daryl', 'Co-Founder / President', 'R&D Documentation and Tax Credit Strategy',
 'Research and document all Setlistr R&D activities for Section 41 payroll tax credit, IRAP, and NSF SBIR eligibility.',
 'Reconstructed full R&D timeline from January 2026 through May 2026. Estimated 450-500 hours of founder R&D time. Documented 16 technical phases covering product concept through patent strategy. Built R&D time tracking system in Supabase with AI-assisted entry structuring. Identified backup records to collect: GitHub commits, ACRCloud testing records, app screenshots, contractor messages, calendar meetings, legal drafts.',
 25,
 'R&D documentation system live in Setlistr admin panel. 14 technical entries retroactively logged. Conservative estimate: 450-500 hours Jan-May 2026.',
 'Formal payroll records and engineering time logs needed to strengthen tax credit claim. CPA review required before filing.',
 'R&D tracker / this document',
 ARRAY['Section 41', 'IRAP', 'NSF SBIR'],
 true),

('2026-05-01', 'Daryl', 'Co-Founder / President', 'VLA Patent Pro Bono Application',
 'Research and apply to Volunteer Lawyers for the Arts Patent Pro Bono Program for artist-inventors to obtain free patent prosecution counsel.',
 'Researched VLA Patent Pro Bono Program eligibility. Confirmed Jesse''s SOCAN registration (IPI 632679232) as qualifying artist credential. Prepared application materials: list of 9 PPAs with filing dates, description of invention areas, pre-revenue financial status documentation. Submitted application to VLA referencing artist-inventor status and provisional patent expiry timeline.',
 10,
 'VLA application submitted. Parallel application submitted to USPTO Tennessee regional pro bono program. Vanderbilt IP/Arts Clinic also contacted.',
 'Pro bono programs have limited capacity. Acceptance not guaranteed. Wilson Sonsini introduction via Scott Trainer remains primary patent counsel path.',
 'Application docs',
 ARRAY['Section 41', 'Patent'],
 true);
