// setlistr-2/app/terms/page.tsx

export const metadata = {
  title: 'Terms of Service — Setlistr',
  description: 'Setlistr Terms of Service',
};

export default function TermsPage() {
  return (
    <div style={{
      background: '#0a0908',
      minHeight: '100vh',
      color: '#f2f1f0',
      fontFamily: '"DM Sans", sans-serif',
      padding: '60px 24px',
    }}>
      <div style={{ maxWidth: 720, margin: '0 auto' }}>

        {/* Header */}
        <div style={{ marginBottom: 48, borderBottom: '1px solid #2a2520', paddingBottom: 32 }}>
          <p style={{ color: '#c9a84c', fontSize: 11, fontFamily: '"DM Mono", monospace', letterSpacing: 2, textTransform: 'uppercase', marginBottom: 12 }}>
            Legal
          </p>
          <h1 style={{ fontSize: 32, fontWeight: 700, color: '#f2f1f0', marginBottom: 12 }}>
            Terms of Service
          </h1>
          <p style={{ color: '#888', fontSize: 13 }}>Last Updated: May 6, 2026</p>
        </div>

        <Section title="About Setlistr">
          <P>Setlistr is a technology platform designed to help artists, songwriters, performers, managers, bands, publishers, labels, venues, and authorized representatives identify songs performed during live events, generate and review setlists, organize performance information, and prepare or submit performance data to performing rights organizations, collection societies, rights administrators, publishers, venues, or other third parties.</P>
          <P>Setlistr uses audio fingerprinting, metadata matching, user input, performance data, catalogue information, timestamps, venue information, and third-party integrations to assist with song identification, setlist creation, setlist review, royalty-related reporting, and performance data organization.</P>
          <P>Setlistr is a technology tool. Setlistr is not a performing rights organization, collection society, music publisher, royalty administrator, legal representative, accounting firm, financial advisor, or payment processor for royalties.</P>
          <P>Setlistr does not guarantee that any song will be identified, that any setlist will be complete or accurate, that any performance information will be accepted or processed by a third party, or that any royalties, fees, payments, credits, or other compensation will be received.</P>
          <P>Any song matches, setlist suggestions, confidence scores, missing song indicators, royalty estimates, submission tools, or performance data generated by the Service are provided for review and assistance only. You are responsible for reviewing, confirming, correcting, and approving all information before submitting it to any third party.</P>
        </Section>

        <Section title="Acceptance of These Terms">
          <P>These Terms of Service (&ldquo;Terms&rdquo;) govern your access to and use of Setlistr, including our mobile application, website, software, tools, features, data services, and related services (the &ldquo;Service&rdquo;). These Terms form a legally binding agreement between you and Setlistr, Inc. (&ldquo;Setlistr,&rdquo; &ldquo;we,&rdquo; &ldquo;us,&rdquo; or &ldquo;our&rdquo;).</P>
          <P>By downloading the Setlistr app, creating an account, accessing the Service, or using any part of the Service, you agree to these Terms and to our Privacy Policy. If you do not agree to these Terms, you may not access or use the Service.</P>
          <P>By using the Service, you confirm that: (a) you have read, understood, and agree to be bound by these Terms; (b) you have the legal authority to enter into these Terms personally or on behalf of the artist, songwriter, performer, band, company, organization, rights holder, minor, or other party you represent; (c) if you are under the age of majority in your jurisdiction, your parent, legal guardian, or authorized adult representative has reviewed and agreed to these Terms on your behalf; and (d) all information you provide to Setlistr is accurate, current, and complete.</P>
        </Section>

        <Section title="Eligibility">
          <P>You may use the Service only if you are legally permitted to do so in your jurisdiction. If you are under the age of majority in your jurisdiction, you may use the Service only with the consent and supervision of a parent, legal guardian, manager, label, publisher, or other authorized adult representative who has reviewed and agreed to these Terms on your behalf.</P>
        </Section>

        <Section title="Children's Privacy and Users Under 13">
          <P>Setlistr is not directed to children under the age of 13. Users under the age of 13 may not create an account, submit personal information, or use the Service unless permitted by applicable law and managed by a parent, legal guardian, or authorized adult representative in a manner that complies with applicable children&apos;s privacy laws, including COPPA where applicable.</P>
          <P>If you are a parent or legal guardian and believe that a child under 13 has provided personal information to Setlistr without required consent, please contact us at info@setlistr.ai.</P>
        </Section>

        <Section title="Account Registration">
          <P>To access certain features of the Service, you may be required to create an account. You agree to provide accurate, complete, and current information, maintain the confidentiality of your login credentials, notify Setlistr promptly if you believe your account has been accessed without authorization, and not create or use an account for any fraudulent, misleading, unlawful, or unauthorized purpose.</P>
          <P>You are responsible for all activity that occurs under your account, whether or not you authorized that activity.</P>
        </Section>

        <Section title="Authority to Use the Service">
          <P>Because Setlistr may be used to identify songs, generate setlists, organize performance data, and prepare or submit performance information, you must have the proper authority to use the Service in connection with any artist, songwriter, performer, band, venue, performance, catalogue, copyright, royalty claim, or rights holder.</P>
          <P>You may not use Setlistr to submit, prepare, create, manipulate, or support any false, fraudulent, misleading, duplicate, unauthorized, or improper performance claim, royalty claim, setlist submission, ownership claim, rights claim, or related submission.</P>
        </Section>

        <Section title="Audio Fingerprinting and Song Identification">
          <P>Setlistr uses audio fingerprinting and music identification technology to help identify songs performed during live events. When you enable song identification features, Setlistr may temporarily process short portions of audio for the limited purpose of generating audio fingerprints, matching those fingerprints against third-party or internal music identification databases, and returning possible song matches for your review.</P>
          <P>When you use live, real-time song identification during a performance, Setlistr does not store the audio itself — short audio segments are processed only to generate audio fingerprints and are not retained after processing.</P>
          <P>If you upload an audio or video recording of a performance (for example, through the Upload a Show feature), Setlistr stores that recording in order to generate your setlist and as a record of the performance. Uploaded recordings are retained until you request deletion. To request deletion of an uploaded recording, contact us at info@setlistr.ai.</P>
          <P>Setlistr does not claim ownership of any musical work, sound recording, live performance, lyrics, composition, master recording, publishing rights, neighboring rights, performance rights, or other intellectual property identified, referenced, processed, or matched through the Service.</P>
        </Section>

        <Section title="Song Identification Accuracy">
          <P>You understand and agree that song identification results generated by the Service may be incomplete, inaccurate, unavailable, delayed, or incorrect. Live performance conditions may affect identification results, including crowd noise, poor audio quality, altered arrangements, live versions, acoustic versions, medleys, covers, remixes, unreleased songs, instrumental sections, extended introductions, tuning breaks, and other factors.</P>
          <P>Any song matches, confidence scores, missing song indicators, possible matches, suggested setlists, timestamps, metadata, or related information generated by the Service are provided for review and assistance only. You are responsible for reviewing, confirming, correcting, approving, and submitting all information before any submission is made.</P>
        </Section>

        <Section title="Performing Rights Organizations and Third-Party Submissions">
          <P>Setlistr may help users prepare, organize, transmit, support, or submit performance information to performing rights organizations (PROs) including SOCAN, ASCAP, BMI, PRS, APRA, SESAC, GMR, and other collection societies, royalty administrators, publishers, venues, or other third parties.</P>
          <P>Setlistr is not a performing rights organization, collection society, music publisher, royalty administrator, payment processor for royalties, legal representative, accounting firm, or financial advisor. Setlistr does not control and is not responsible for the policies, decisions, processing times, requirements, royalty calculations, payment timelines, disputes, rejections, approvals, or actions of any PRO or other third party.</P>
          <P>You are responsible for maintaining your own memberships, registrations, catalogue information, ownership information, split information, tax information, and eligibility requirements with any applicable performing rights organization or other third party.</P>
        </Section>

        <Section title="Royalties, Payments, and Estimates">
          <P>Setlistr may display royalty estimates, estimated claim values, estimated performance values, projected payments, or other financial information related to performances, setlists, or submissions. Any such estimates are provided for informational purposes only and are not guaranteed.</P>
          <P>Setlistr does not guarantee that any estimated amount will be collected, recovered, paid, approved, processed, or received. Any Setlistr service fees, commissions, administration fees, revenue shares, transaction fees, subscription fees, or other charges will be disclosed through the Service or in applicable payment terms before they apply.</P>
        </Section>

        <Section title="No Legal, Financial, Tax, or Royalty Advice">
          <P>The Service is for technology, workflow, song identification, setlist organization, and performance data assistance only. Setlistr does not provide legal, financial, tax, accounting, royalty administration, publishing, copyright, or business advice. You should consult your own legal, financial, tax, accounting, publishing, or royalty advisors regarding your rights, obligations, registrations, royalties, ownership, taxes, contracts, disputes, or claims.</P>
        </Section>

        <Section title="User Content and License">
          <P>&ldquo;User Content&rdquo; means any information, data, materials, or content that you submit, upload, enter, create, confirm, correct, approve, transmit, or otherwise provide through the Service, including setlists, artist information, song information, venue information, performance information, catalogue information, expected covers, corrections, notes, metadata, and submission information.</P>
          <P>You retain ownership of your User Content. By submitting User Content through the Service, you grant Setlistr a worldwide, non-exclusive, royalty-free license to host, store, process, analyze, transmit, display, reproduce, modify, format, organize, and otherwise use your User Content as reasonably necessary to operate, provide, maintain, protect, and improve the Service.</P>
        </Section>

        <Section title="Prohibited Conduct">
          <P>You agree not to: submit any false, fraudulent, misleading, duplicate, unauthorized, or improper setlist, royalty claim, rights claim, ownership claim, performance claim, or related submission; claim performances, songs, royalties, rights, credits, ownership, or payments you are not authorized to claim; impersonate any artist, songwriter, performer, band, manager, publisher, label, venue, company, rights holder, or other person or organization; violate any applicable law, rule, regulation, venue policy, event policy, app store policy, platform requirement, third-party right, contract, or agreement; interfere with, disrupt, damage, overload, or impair the Service; attempt to gain unauthorized access to the Service, user accounts, systems, networks, databases, or data; copy, scrape, crawl, harvest, extract, or collect data from the Service except as expressly permitted; reverse engineer, decompile, disassemble, modify, clone, copy, sell, resell, lease, license, sublicense, or create derivative works based on the Service; bypass, disable, or undermine any security, fraud prevention, access control, usage limitation, or technical protection measure; use bots, scripts, automation, or other automated means to access or abuse the Service; or use the Service in any way that creates legal risk, security risk, fraud risk, reputational harm, or operational harm.</P>
        </Section>

        <Section title="Setlistr Intellectual Property">
          <P>Setlistr and its licensors own all rights, title, and interest in and to the Service, including the Setlistr app, website, software, technology, source code, algorithms, audio fingerprinting workflows, data processing systems, databases, user interface, designs, layouts, graphics, logos, trademarks, service marks, trade names, branding, documentation, features, functionality, and all related intellectual property rights.</P>
          <P>Except for the limited right to use the Service in accordance with these Terms, no rights are granted to you in or to Setlistr&apos;s intellectual property. You may not copy, modify, reproduce, distribute, sell, license, sublicense, reverse engineer, decompile, disassemble, scrape, extract, clone, or create derivative works based on the Service or any part of the Service without Setlistr&apos;s prior written permission.</P>
        </Section>

        <Section title="Disclaimers and No Warranty">
          <P>THE SERVICE IS PROVIDED ON AN &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; BASIS. SETLISTR MAKES NO WARRANTIES, REPRESENTATIONS, OR GUARANTEES OF ANY KIND, WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, INCLUDING ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, NON-INFRINGEMENT, ACCURACY, AVAILABILITY, RELIABILITY, SECURITY, UNINTERRUPTED OPERATION, OR ERROR-FREE PERFORMANCE. Some jurisdictions do not allow certain warranty exclusions, so some of the above exclusions may not apply to you.</P>
        </Section>

        <Section title="Limitation of Liability">
          <P>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, SETLISTR, ITS OWNERS, DIRECTORS, OFFICERS, EMPLOYEES, CONTRACTORS, AGENTS, LICENSORS, SERVICE PROVIDERS, AFFILIATES, SUCCESSORS, AND ASSIGNS WILL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, PUNITIVE, OR ENHANCED DAMAGES, INCLUDING LOST PROFITS, LOST ROYALTIES, LOST REVENUE, LOST BUSINESS OPPORTUNITIES, LOST DATA, REPUTATIONAL HARM, BUSINESS INTERRUPTION, MISSED SUBMISSIONS, REJECTED SUBMISSIONS, DELAYED PAYMENTS, MISSED PAYMENTS, INCORRECT ROYALTY ESTIMATES, INCORRECT SONG MATCHES, FAILURE TO IDENTIFY SONGS, OWNERSHIP DISPUTES, RIGHTS DISPUTES, OR CLAIMS BY THIRD PARTIES.</P>
          <P>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, SETLISTR&apos;S TOTAL LIABILITY FOR ANY CLAIM ARISING OUT OF OR RELATING TO THE SERVICE OR THESE TERMS WILL NOT EXCEED THE GREATER OF: (A) THE AMOUNT YOU PAID TO SETLISTR FOR THE SERVICE IN THE THREE MONTHS BEFORE THE EVENT GIVING RISE TO THE CLAIM; OR (B) ONE HUNDRED U.S. DOLLARS (USD $100). Some jurisdictions do not allow certain limitations of liability, so some of the above limitations may not apply to you.</P>
        </Section>

        <Section title="Indemnification">
          <P>You agree to defend, indemnify, and hold harmless Setlistr, its owners, directors, officers, employees, contractors, agents, licensors, service providers, affiliates, successors, and assigns from and against any claims, demands, disputes, losses, liabilities, damages, costs, expenses, penalties, fines, and fees, including reasonable legal fees, arising out of or related to: your access to or use of the Service; any User Content you submit or provide through the Service; any claim that you lacked the required rights, permissions, consents, or authority to use the Service or act on behalf of any artist, songwriter, performer, band, minor, manager, publisher, label, venue, rights holder, or other party; any false, fraudulent, misleading, duplicate, unauthorized, inaccurate, improper, or unlawful setlist, royalty claim, rights claim, ownership claim, performance claim, submission, or related information; any dispute involving copyrights, publishing rights, performance rights, ownership, splits, royalties, credits, catalogue information, or third-party rights; or your violation of these Terms or applicable law.</P>
        </Section>

        <Section title="Suspension and Termination">
          <P>Setlistr may suspend, restrict, disable, or terminate your account, access to the Service, submissions, data, or any feature at any time if Setlistr reasonably believes you have violated these Terms, provided false or unauthorized information, created legal risk, security risk, or fraud risk, failed to pay required fees, or if Setlistr decides to discontinue or materially change all or part of the Service.</P>
          <P>You may stop using the Service at any time. You may request account deletion as described in the Privacy Policy or through any account tools made available by Setlistr.</P>
        </Section>

        <Section title="Dispute Resolution">
          <P>Before starting any formal legal proceeding, you agree to first contact Setlistr and attempt to resolve the dispute informally by sending written notice to info@setlistr.ai. Setlistr will have thirty days to attempt to resolve the dispute informally.</P>
          <P>If the dispute cannot be resolved informally, you and Setlistr agree that any dispute, claim, or controversy arising out of or relating to these Terms or the Service will be resolved by binding arbitration on an individual basis, administered under the rules of a recognized arbitration provider selected by Setlistr, except where prohibited by applicable law.</P>
          <P>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, YOU AND SETLISTR AGREE THAT ANY DISPUTE WILL BE BROUGHT ONLY ON AN INDIVIDUAL BASIS AND NOT AS PART OF A CLASS ACTION, REPRESENTATIVE ACTION, COLLECTIVE ACTION, GROUP ACTION, MASS ARBITRATION, OR SIMILAR PROCEEDING.</P>
        </Section>

        <Section title="Governing Law">
          <P>These Terms and any dispute, claim, or controversy arising out of or relating to these Terms or the Service will be governed by the laws of the State of Delaware, without regard to conflict of law principles.</P>
        </Section>

        <Section title="Changes to These Terms">
          <P>Setlistr may update or modify these Terms from time to time. If we make material changes, we may provide notice through the Service, by email, in-app message, or another reasonable method. Your continued access to or use of the Service after updated Terms become effective means you accept the updated Terms.</P>
        </Section>

        <Section title="Contact Information">
          <P>For questions about these Terms, the Service, privacy, account support, legal notices, or other matters, contact us at:</P>
          <div style={{ background: '#141210', border: '1px solid #2a2520', borderRadius: 8, padding: '20px 24px', marginTop: 8, fontFamily: '"DM Mono", monospace', fontSize: 13, lineHeight: 2, color: '#c9a84c' }}>
            <div>Setlistr, Inc.</div>
            <div>517 E Campbell Road</div>
            <div>Madison, TN 37115</div>
            <div>Email: info@setlistr.ai</div>
            <div>Website: https://setlistr.ai</div>
            <div>Terms of Service: https://setlistr.ai/terms</div>
            <div>Privacy Policy: https://setlistr.ai/privacy</div>
          </div>
        </Section>

      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: 36 }}>
      <h2 style={{
        fontSize: 16,
        fontWeight: 700,
        color: '#f2f1f0',
        marginBottom: 12,
        paddingBottom: 8,
        borderBottom: '1px solid #2a2520',
      }}>
        {title}
      </h2>
      {children}
    </div>
  );
}

function P({ children }: { children: React.ReactNode }) {
  return (
    <p style={{ fontSize: 14, lineHeight: 1.75, color: '#b8b0a8', marginBottom: 12 }}>
      {children}
    </p>
  );
}
